### ISSUE TITLE
[Feature Request] path module

### ISSUE THREAD

**Issue by TurtleP** [1bardesign/batteries#27]
## About

Discussed on Discord briefly, it would be nice to have a simple path module. These could also be appended to the existing stringx module instead, specifying they operate on file paths/file names.

## Functions

1. `{module}.extractFilename` - get the filename of a file
    - Useful for when iterating and requiring lua files
2. `{module}.extract(File)Extension` - get the extension of a file
3. Some function that [wraps around doing this](https://github.com/TurtleP/nest/blob/master/nest/init.lua#L4) for the `init.lua` path

While the first two functions are simple to do, I think it would still be beneficial to have them. Maybe have a function that would also return both pieces of information, should the user want both from one function call.

**Comment by 1bardesign** [comment]
I don't think this makes sense for batteries, because it would need to be exported unconditionally as a global to be of any use for requires.

- if it's not, modules depending on it would have to do so "unsafely", which is the opposite of what they want if they're requiring all of their dependencies explicitly
- if it does, then it violates the intent of :export()

for parsing basename.extension type stuff, i can see the use basically as a wrapper on `stringx.split`, but a whole module for that seems excessive?

`stringx.basename_extension` with multi-return is a welcome addition if you're game. My intent at this stage is to leave this open for a while and then close it though.

**Comment by TurtleP** [comment]
Yeah, I can see your points about this. I'll try my hand at the latter, probably.

However, require relatively to the current directory is something useful... Definitely something that could be in stringx if we just need the path. Could have it use the other function I mentioned, too, if necessary.

**Comment by 1bardesign** [comment]
This can be done fairly trivially with gsub though, I don't see any real benefit.

If you're _not_ relying on batteries `:export()`/globals (as you essentially _cannot_ in an arbitrary library setting) then you have to do some set up each time anyway, which could be used to just set up the relative require path.

It's a silly limitation of lua, I agree, but I don't think batteries can do much about this.

It cannot really know the correct string to remove from the passed path vararg safely without a bunch of logic dependent on your require path and file structure. You can't just remove the last dot section because you could include a different filename. There's no guarantee that the extension is `.lua` if you've added other parsers like moonscript or urn.

The pattern i use in batteries is:
```lua
local path = (...):gsub("tablex", "") --strip out the actual name of the current module
local assert = require(path .. "assert") --append the name of the module to require here
```
just as good is
```lua
--replace the current name directly; results in a bunch of duplicated current name if used extensively
local assert = require((...):gsub("tablex", "assert"))
```

In my opinion this is just as terse as a general case relative require would be; especially if it "needs" to work in a no-export environment (as you'd have to require batteries based on absolute path, and then generate relative paths from there)

**Comment by idbrii** [comment]
[penlight's path](https://github.com/lunarmodules/Penlight/blob/master/lua/pl/path.lua) ([docs](https://lunarmodules.github.io/Penlight/libraries/pl.path.html)) is an example of what a path module might do, but not sure it makes sense to wrap love.filesystem like they do. I seems like it'd be mostly a path building library, but since love accepts posix file paths on windows, that's pretty simple too.

Some of penlight's helpers like [isfile](https://lunarmodules.github.io/Penlight/libraries/pl.path.html#isfile) seem pointless compared to `love.filesystem.newFile` since you probably want to *do* something with the file anyway and will need to newFile.

Maybe there's more useful things in there, but I didn't dig any deeper.

**Comment by 1bardesign** [comment]
Closing this now as i don't think it's likely to be of much use.
